version = 0.1

[default.deploy.parameters]
stack_name = "securechat-task2-ingest"
resolve_s3 = true
s3_prefix = "securechat-task2-ingest"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "us-east-1"
